ingressgateway:
  name: "istio-ingressgateway"

egressgateway:
  name: "istio-egressgateway"

  service:
    type: ClusterIP

istiod:
  sidecarInjectorWebhook:
    enableNamespacesByDefault: true

  global:
    logAsJson: true
    mountMtlsCerts: true

  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true