vault:
  server:
    standalone:
      enabled: true
      config: |
        ui = true
        disable_mlock = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "file" {
          path = "/vault/data"
        }

vault-autounseal:
  settings:
    vault_url: "http://vault.vault.svc.cluster.local:8200"

external-vault:
  name: "vault"
  hosts:
    - vault.clustergaming.com
  service:
    route:
      http:
      - route:
        - destination:
            host: vault.vault.svc.cluster.local
            port:
              number: 8200   


vault-secrets-operator:
  defaultVaultConnection:
    enabled: true

    address: "http://vault.vault.svc.cluster.local:8200"
    skipTLSVerify: false

  defaultAuthMethod:
    enabled: true
    method: kubernetes
    mount: kubernetes

    kubernetes:
      role: "read"
      serviceAccount: default
      tokenAudiences:
        - vault