apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "devops@exzeo.com"
    privateKeySecretRef:
      name: cert-manager-pk
    solvers:
      - dns01:
          route53:
            region: us-east-1