apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: krausefire@gmail.com
    privateKeySecretRef:
      name: cert-manager-pk
    dns01:
      godaddy:
        key: fYftG1uFZYTQ_LRx5iH7KU6rR45YjAN2bka
        secret: R5xJGK12LGeS1NbCZuBvhv
