cert-manager:
  installCRDs: true

  ingressShim:
    defaultIssuerName: "cert-manager-issuer"
    defaultIssuerKind: "ClusterIssuer"
    defaultIssuerGroup: "cert-manager.io"

  startupapicheck:
    podLabels:
      sidecar.istio.io/inject: "false"

godaddy-webhook:
  groupName: acme.clustergames.com