external-dns:
  deploymentStrategy:
    type: RollingUpdate

  podLabels:
    app: external-dns

  domainFilters:
    - clustergaming.com

  provider: godaddy 
  txtPrefix: external-dns.
  txtOwnerId: home-dev
  
  extraArgs: 
    - --godaddy-api-key=$(godaddy_key)
    - --godaddy-api-secret=$(godaddy_secret)

  env:
    - name: godaddy_key
      valueFrom:
        secretKeyRef:
          name: godaddy-api-key
          key: key
    - name: godaddy_secret
      valueFrom:
        secretKeyRef:
          name: godaddy-api-key
          key: secret
  sources:
    - service
    - ingress
    - istio-gateway

  # serviceMonitor:
  #   enabled: true

  resources:
    requests:
      memory: "80Mi"
      cpu: "25m"
    limits:
      memory: "125Mi"
      cpu: "50m"