argocd:
  configs:
    cm:
      timeout.reconciliation: 30s
      url: "https://argocd.clustergaming.com"

    rbac:
      policy.default: role:admin
    params:
      server.insecure: true

  applicationSet:
    replicas: 1

  controller:
    replicas: 1
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true

  # server:
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true

    # resources:
    #   limits:
    #     cpu: 200m
    #     memory: 400Mi
    #   requests:
    #     cpu: 150m
    #     memory: 200Mi

  # repoServer:
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true

    # resources:
    #   limits:
    #     cpu: 200m
    #     memory: 400Mi
    #   requests:
    #     cpu: 150m
    #     memory: 250Mi

external-argocd:
  name: "argocd"
  hosts:
    - argocd.clustergaming.com
  service:
    route:
      http:
        - route:
            - destination:
                host: argocd-server.argocd.svc.cluster.local
                port:
                  number: 443