apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cert-manager-static-secret
spec:
  type: kv-v2
  mount: kv
  path: cert-manager/godaddy
  destination:
    name: godaddy-api-key
    create: true
    labels:
      app.kubernetes.io/part-of: "argocd"
  refreshAfter: 30s