name: Automatic Rebase

on: pull_request

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}